import { useEffect, useState } from 'react';
import { useTaskStore } from '@mindwtr/core';
import { PlainCaptureSheet } from './PlainCaptureSheet';

export const QUICK_CAPTURE_EVENT = 'mindwtr:quick-add';
type CaptureDetail = { initialProps?: unknown; initialValue?: string; expandContent?: boolean; captureMode?: string; captureUi?: string };

// Migration boundary for the existing event bus. Contextual capture (calendar
// slots, project-specific drafts, speech and imports) stays in the legacy host;
// blank text capture uses the new form. No task syntax is generated by this UI.
export function isPlainCaptureRequest(detail: CaptureDetail | null | undefined, defaultCaptureMethod?: string): boolean {
    return !detail?.initialProps && !detail?.initialValue && !detail?.expandContent
        && detail?.captureUi !== 'advanced'
        && detail?.captureMode !== 'audio'
        && (detail?.captureMode === 'text' || defaultCaptureMethod !== 'audio');
}

export function PwaCaptureHost() {
    const [open, setOpen] = useState(false);
    useEffect(() => {
        const receive = (event: Event) => {
            const detail = (event as CustomEvent<CaptureDetail>).detail;
            if (!isPlainCaptureRequest(detail, useTaskStore.getState().settings.gtd?.defaultCaptureMethod)) return;
            // Do not stack a second capture over an existing legacy modal or an
            // unsaved editor. Let its existing event handling retain ownership.
            if (document.querySelector('[role="dialog"]:not([data-testid="plain-capture-sheet"])')) return;
            // Capture-phase routing runs before the legacy window listener,
            // independent of React effect registration order or StrictMode.
            event.stopImmediatePropagation();
            setOpen(true);
        };
        window.addEventListener(QUICK_CAPTURE_EVENT, receive, true);
        return () => window.removeEventListener(QUICK_CAPTURE_EVENT, receive, true);
    }, []);
    return <PlainCaptureSheet isOpen={open} onClose={() => setOpen(false)} onAdvanced={() => {
        setOpen(false);
        window.dispatchEvent(new CustomEvent(QUICK_CAPTURE_EVENT, { detail: { captureUi: 'advanced' } }));
    }} />;
}
